"""This module contains functions to preprocess the mock data.

This script provides functions to clean and prepare the mock data generated by 
`data_collector.py`. It includes text cleaning for the NLP data, a simulation of 
image preprocessing for the vision data, and one-hot encoding for the recommendation 
data. These preprocessing steps are essential for preparing the data for use in 
machine learning models.
"""
import os
import pandas as pd

def preprocess_nlp_data(
    input_file: str = os.getenv("NLP_INPUT_FILE", "ImplementationAi/data/mock_nlp_data.csv"),
    output_file: str = os.getenv("NLP_OUTPUT_FILE", "ImplementationAi/data/processed_nlp_data.csv"),
) -> None:
    """Preprocesses the NLP data by cleaning the text.

    Args:
        input_file (str): The path to the input CSV file.
        output_file (str): The path to the output CSV file.
    """
    print("Preprocessing NLP data...")
    df = pd.read_csv(input_file)
    # Logic: Clean text (lowercase and remove non-alphanumeric/whitespace characters) to standardize input for the NLP model.
    # Flow: Creates a new 'text_cleaned' column in the DataFrame.
    # AI Preprocessing Activity: Prepares text data for use in the NLP model.
    df["text_cleaned"] = df["text"].str.lower().str.replace(r"[^\\w\\s]", "", regex=True)
    df.to_csv(output_file, index=False)
    print(f"Processed NLP data saved to {output_file}")

def preprocess_vision_data(
    input_dir: str = os.getenv("VISION_INPUT_DIR", "ImplementationAi/data/mock_vision_data"),
    output_dir: str = os.getenv("VISION_OUTPUT_DIR", "ImplementationAi/data/processed_vision_data"),
) -> None:
    """Simulates preprocessing of vision data.

    Args:
        input_dir (str): The path to the input directory.
        output_dir (str): The path to the output directory.
    """
    print("Preprocessing Vision data...")
    os.makedirs(output_dir, exist_ok=True)
    # Logic: Simulates real image preprocessing steps (e.g., resizing, normalization).
    # Flow: Creates dummy output files with a 'processed_' prefix for image data.
    # AI Preprocessing Activity: Simulates resizing/normalizing image data.
    for filename in os.listdir(input_dir):
        if filename.endswith((".jpg", ".png")):
            # In a real scenario, this would involve resizing, normalization, etc.
            # For this mock, we just create a dummy processed file.
            processed_filepath = os.path.join(output_dir, f"processed_{filename}")
            with open(processed_filepath, "w", encoding="utf-8") as f:
                f.write(f"processed data for {filename}")
    print(f"Processed Vision data saved to {output_dir}")

def preprocess_recommendation_data(
    input_file: str = os.getenv("REC_INPUT_FILE", "ImplementationAi/data/mock_recommendation_data.csv"),
    output_file: str = os.getenv("REC_OUTPUT_FILE", "ImplementationAi/data/processed_recommendation_data.csv"),
) -> None:
    """Preprocesses recommendation data using one-hot encoding.

    Args:
        input_file (str): The path to the input CSV file.
        output_file (str): The path to the output CSV file.
    """
    print("Preprocessing Recommendation data...")
    df = pd.read_csv(input_file)
    # Logic: Uses one-hot encoding for categorical variables (dietary_preferences, health_goals).
    # Flow: Prepares data for machine learning models that require numerical inputs.
    # AI Preprocessing Activity: One-hot encodes categorical variables to create numerical features for the Recommendation model.
    df = pd.get_dummies(
        df, columns=["dietary_preferences", "health_goals"], prefix=["diet", "goal"]
    )
    df.to_csv(output_file, index=False)
    print(f"Processed Recommendation data saved to {output_file}")

def run_all_preprocessing():
    # Flow: When run directly, performs preprocessing for all datasets.
    preprocess_nlp_data(
        input_file=os.getenv("NLP_INPUT_FILE", "ImplementationAi/data/mock_nlp_data.csv"),
        output_file=os.getenv("NLP_OUTPUT_FILE", "ImplementationAi/data/processed_nlp_data.csv"),
    )
    preprocess_vision_data(
        input_dir=os.getenv("VISION_INPUT_DIR", "ImplementationAi/data/mock_vision_data"),
        output_dir=os.getenv("VISION_OUTPUT_DIR", "ImplementationAi/data/processed_vision_data"),
    )
    preprocess_recommendation_data(
        input_file=os.getenv("REC_INPUT_FILE", "ImplementationAi/data/mock_recommendation_data.csv"),
        output_file=os.getenv("REC_OUTPUT_FILE", "ImplementationAi/data/processed_recommendation_data.csv"),
    )

if __name__ == "__main__":
    run_all_preprocessing()